__author__ = "Leandro Poli"
__copyright__ = "Copyright 2018, Decoder"
__license__ = "GPLv3"
__version__ = "1.1.2"
__maintainer__ = __author__
__status__ = "Production"


def hex_to_utf8(value):
    """
    Converts hex characters to UTF-8
    :param value: String to convert
    :return: String with characters converted
    """
    return value.replace("\\r", " ") \
                .replace("\\xa0", " ") \
                .replace("\\x21", "!") \
                .replace("\\x22", "\"") \
                .replace("\\x23", "#") \
                .replace("\\x24", "$") \
                .replace("\\x25", "%") \
                .replace("\\x26", "&") \
                .replace("\\x27", "'") \
                .replace("\\x28", "(") \
                .replace("\\x29", ")") \
                .replace("\\x2a", "*") \
                .replace("\\x2b", "+") \
                .replace("\\x2c", ",") \
                .replace("\\x2d", "-") \
                .replace("\\x2e", ".") \
                .replace("\\x2f", "/") \
                .replace("\\x30", "0") \
                .replace("\\x31", "1") \
                .replace("\\x32", "2") \
                .replace("\\x33", "3") \
                .replace("\\x34", "4") \
                .replace("\\x35", "5") \
                .replace("\\x36", "6") \
                .replace("\\x37", "7") \
                .replace("\\x38", "8") \
                .replace("\\x39", "9") \
                .replace("\\x3a", ":") \
                .replace("\\x3b", ";") \
                .replace("\\x3c", "<") \
                .replace("\\x3d", "=") \
                .replace("\\x3e", ">") \
                .replace("\\x3f", "?") \
                .replace("\\x40", "@") \
                .replace("\\x41", "A") \
                .replace("\\x42", "B") \
                .replace("\\x43", "C") \
                .replace("\\x44", "D") \
                .replace("\\x45", "E") \
                .replace("\\x46", "F") \
                .replace("\\x47", "G") \
                .replace("\\x48", "H") \
                .replace("\\x49", "I") \
                .replace("\\x4a", "J") \
                .replace("\\x4b", "K") \
                .replace("\\x4c", "L") \
                .replace("\\x4d", "M") \
                .replace("\\x4e", "N") \
                .replace("\\x4f", "O") \
                .replace("\\x50", "P") \
                .replace("\\x51", "Q") \
                .replace("\\x52", "R") \
                .replace("\\x53", "S") \
                .replace("\\x54", "T") \
                .replace("\\x55", "U") \
                .replace("\\x56", "V") \
                .replace("\\x57", "W") \
                .replace("\\x58", "X") \
                .replace("\\x59", "Y") \
                .replace("\\x5a", "Z") \
                .replace("\\x5b", "[") \
                .replace("\\x5c", "\\") \
                .replace("\\x5d", "]") \
                .replace("\\x5e", "^") \
                .replace("\\x5f", "_") \
                .replace("\\x60", "`") \
                .replace("\\x61", "a") \
                .replace("\\x62", "b") \
                .replace("\\x63", "c") \
                .replace("\\x64", "d") \
                .replace("\\x65", "e") \
                .replace("\\x66", "f") \
                .replace("\\x67", "g") \
                .replace("\\x68", "h") \
                .replace("\\x69", "i") \
                .replace("\\x6a", "j") \
                .replace("\\x6b", "k") \
                .replace("\\x6c", "l") \
                .replace("\\x6d", "m") \
                .replace("\\x6e", "n") \
                .replace("\\x6f", "o") \
                .replace("\\x70", "p") \
                .replace("\\x71", "q") \
                .replace("\\x72", "r") \
                .replace("\\x73", "s") \
                .replace("\\x74", "t") \
                .replace("\\x75", "u") \
                .replace("\\x76", "v") \
                .replace("\\x77", "w") \
                .replace("\\x78", "x") \
                .replace("\\x79", "y") \
                .replace("\\x7a", "z") \
                .replace("\\x7b", "{") \
                .replace("\\x7c", "|") \
                .replace("\\x7d", "}") \
                .replace("\\x7e", "~") \
                .replace("\\xc2\\xa1", "¡") \
                .replace("\\xc2\\xa2", "¢") \
                .replace("\\xc2\\xa3", "£") \
                .replace("\\xc2\\xa4", "¤") \
                .replace("\\xc2\\xa5", "¥") \
                .replace("\\xc2\\xa6", "¦") \
                .replace("\\xc2\\xa7", "§") \
                .replace("\\xc2\\xa8", "¨") \
                .replace("\\xc2\\xa9", "©") \
                .replace("\\xc2\\xaa", "ª") \
                .replace("\\xc2\\xab", "«") \
                .replace("\\xc2\\xac", "¬") \
                .replace("\\xc2\\xad", "­") \
                .replace("\\xc2\\xae", "®") \
                .replace("\\xc2\\xaf", "¯") \
                .replace("\\xc2\\xb0", "°") \
                .replace("\\xc2\\xb1", "±") \
                .replace("\\xc2\\xb2", "²") \
                .replace("\\xc2\\xb3", "³") \
                .replace("\\xc2\\xb4", "´") \
                .replace("\\xc2\\xb5", "µ") \
                .replace("\\xc2\\xb6", "¶") \
                .replace("\\xc2\\xb7", "·") \
                .replace("\\xc2\\xb8", "¸") \
                .replace("\\xc2\\xb9", "¹") \
                .replace("\\xc2\\xba", "º") \
                .replace("\\xc2\\xbb", "»") \
                .replace("\\xc2\\xbc", "¼") \
                .replace("\\xc2\\xbd", "½") \
                .replace("\\xc2\\xbe", "¾") \
                .replace("\\xc2\\xbf", "¿") \
                .replace("\\xc3\\x80", "À") \
                .replace("\\xc3\\x81", "Á") \
                .replace("\\xc3\\x82", "Â") \
                .replace("\\xc3\\x83", "Ã") \
                .replace("\\xc3\\x84", "Ä") \
                .replace("\\xc3\\x85", "Å") \
                .replace("\\xc3\\x86", "Æ") \
                .replace("\\xc3\\x87", "Ç") \
                .replace("\\xc3\\x88", "È") \
                .replace("\\xc3\\x89", "É") \
                .replace("\\xc3\\x8a", "Ê") \
                .replace("\\xc3\\x8b", "Ë") \
                .replace("\\xc3\\x8c", "Ì") \
                .replace("\\xc3\\x8d", "Í") \
                .replace("\\xc3\\x8e", "Î") \
                .replace("\\xc3\\x8f", "Ï") \
                .replace("\\xc3\\x90", "Ð") \
                .replace("\\xc3\\x91", "Ñ") \
                .replace("\\xc3\\x92", "Ò") \
                .replace("\\xc3\\x93", "Ó") \
                .replace("\\xc3\\x94", "Ô") \
                .replace("\\xc3\\x95", "Õ") \
                .replace("\\xc3\\x96", "Ö") \
                .replace("\\xc3\\x97", "×") \
                .replace("\\xc3\\x98", "Ø") \
                .replace("\\xc3\\x99", "Ù") \
                .replace("\\xc3\\x9a", "Ú") \
                .replace("\\xc3\\x9b", "Û") \
                .replace("\\xc3\\x9c", "Ü") \
                .replace("\\xc3\\x9d", "Ý") \
                .replace("\\xc3\\x9e", "Þ") \
                .replace("\\xc3\\x9f", "ß") \
                .replace("\\xc3\\xa0", "à") \
                .replace("\\xc3\\xa1", "á") \
                .replace("\\xc3\\xa2", "â") \
                .replace("\\xc3\\xa3", "ã") \
                .replace("\\xc3\\xa4", "ä") \
                .replace("\\xc3\\xa5", "å") \
                .replace("\\xc3\\xa6", "æ") \
                .replace("\\xc3\\xa7", "ç") \
                .replace("\\xc3\\xa8", "è") \
                .replace("\\xc3\\xa9", "é") \
                .replace("\\xc3\\xaa", "ê") \
                .replace("\\xc3\\xab", "ë") \
                .replace("\\xc3\\xac", "ì") \
                .replace("\\xc3\\xad", "í") \
                .replace("\\xc3\\xae", "î") \
                .replace("\\xc3\\xaf", "ï") \
                .replace("\\xc3\\xb0", "ð") \
                .replace("\\xc3\\xb1", "ñ") \
                .replace("\\xc3\\xb2", "ò") \
                .replace("\\xc3\\xb3", "ó") \
                .replace("\\xc3\\xb4", "ô") \
                .replace("\\xc3\\xb5", "õ") \
                .replace("\\xc3\\xb6", "ö") \
                .replace("\\xc3\\xb7", "÷") \
                .replace("\\xc3\\xb8", "ø") \
                .replace("\\xc3\\xb9", "ù") \
                .replace("\\xc3\\xba", "ú") \
                .replace("\\xc3\\xbb", "û") \
                .replace("\\xc3\\xbc", "ü") \
                .replace("\\xc3\\xbd", "ý") \
                .replace("\\xc3\\xbe", "þ") \
                .replace("\\xc3\\xbf", "ÿ")\



def windows_1251_to_utf8(value):
    '''
    Converts ISO 8859-5 and Windows-1251 characters to UTF-8
    :param value: String to convert
    :return: String with characters converted
    '''
    return value.replace("â‚¬", "€") \
                .replace("â€š", "‚") \
                .replace("Æ’", "ƒ") \
                .replace("â€ž", "„") \
                .replace("â€¦", "…") \
                .replace("â€ ", "†") \
                .replace("â€¡", "‡") \
                .replace("Ë†", "ˆ") \
                .replace("â€°", "‰") \
                .replace("Å ", "Š") \
                .replace("â€¹", "‹") \
                .replace("Å’", "Œ") \
                .replace("Å½", "Ž") \
                .replace("â€˜", "‘") \
                .replace("â€™", "’") \
                .replace("â€œ", "“") \
                .replace("â€", "”") \
                .replace("â€¢", "•") \
                .replace("â€“", "–") \
                .replace("â€”", "—") \
                .replace("Ëœ", "˜") \
                .replace("â„¢", "™") \
                .replace("Å¡", "š") \
                .replace("â€º", "›") \
                .replace("Å“", "œ") \
                .replace("Å¾", "ž") \
                .replace("Å¸", "Ÿ") \
                .replace("Â ", "") \
                .replace("Â¡", "¡") \
                .replace("Â¢", "¢") \
                .replace("Â£", "£") \
                .replace("Â¤", "¤") \
                .replace("Â¥", "¥") \
                .replace("Â¦", "¦") \
                .replace("Â§", "§") \
                .replace("Â¨", "¨") \
                .replace("Â©", "©") \
                .replace("Âª", "ª") \
                .replace("Â«", "«") \
                .replace("Â¬", "¬") \
                .replace("Â­", "­") \
                .replace("Â®", "®") \
                .replace("Â¯", "¯") \
                .replace("Â°", "°") \
                .replace("Â±", "±") \
                .replace("Â²", "²") \
                .replace("Â³", "³") \
                .replace("Â´", "´") \
                .replace("Âµ", "µ") \
                .replace("Â¶", "¶") \
                .replace("Â·", "·") \
                .replace("Â¸", "¸") \
                .replace("Â¹", "¹") \
                .replace("Âº", "º") \
                .replace("Â»", "»") \
                .replace("Â¼", "¼") \
                .replace("Â½", "½") \
                .replace("Â¾", "¾") \
                .replace("Â¿", "¿") \
                .replace("Ã€", "À") \
                .replace("Ã", "Á") \
                .replace("Ã‚", "Â") \
                .replace("Ãƒ", "Ã") \
                .replace("Ã„", "Ä") \
                .replace("Ã…", "Å") \
                .replace("Ã†", "Æ") \
                .replace("Ã‡", "Ç") \
                .replace("Ãˆ", "È") \
                .replace("Ã‰", "É") \
                .replace("Á‰", "É") \
                .replace("ÃŠ", "Ê") \
                .replace("Ã‹", "Ë") \
                .replace("ÃŒ", "Ì") \
                .replace("Ã", "Í") \
                .replace("Á", "Í") \
                .replace("ÃŽ", "Î") \
                .replace("Ã", "Ï") \
                .replace("Ã", "Ð") \
                .replace("Ã‘", "Ñ") \
                .replace("Ã’", "Ò") \
                .replace("Ã“", "Ó") \
                .replace("Á“", "Ó") \
                .replace("Ã”", "Ô") \
                .replace("Ã•", "Õ") \
                .replace("Ã–", "Ö") \
                .replace("Ã—", "×") \
                .replace("Ã˜", "Ø") \
                .replace("Ã™", "Ù") \
                .replace("Ãš", "Ú") \
                .replace("Áš", "Ú") \
                .replace("Ã›", "Û") \
                .replace("Ãœ", "Ü") \
                .replace("Áœ", "Ü") \
                .replace("Ã", "Ý") \
                .replace("Ãž", "Þ") \
                .replace("ÃŸ", "ß") \
                .replace("Ã ", "à") \
                .replace("Ã¡", "á") \
                .replace("Á¡", "á") \
                .replace("Ã¢", "â") \
                .replace("Ã£", "ã") \
                .replace("Ã¤", "ä") \
                .replace("Ã¥", "å") \
                .replace("Ã¦", "æ") \
                .replace("Ã§", "ç") \
                .replace("Ã¨", "è") \
                .replace("Ã©", "é") \
                .replace("Á©", "é") \
                .replace("Ãª", "ê") \
                .replace("Ã«", "ë") \
                .replace("Ã¬", "ì") \
                .replace("Ã­", "í") \
                .replace("Á­", "í") \
                .replace("Ã®", "î") \
                .replace("Ã¯", "ï") \
                .replace("Ã°", "ð") \
                .replace("Ã±", "ñ") \
                .replace("Á±", "ñ") \
                .replace("Ã²", "ò") \
                .replace("Ã³", "ó") \
                .replace("Á³", "ó") \
                .replace("Ã´", "ô") \
                .replace("Ãµ", "õ") \
                .replace("Ã¶", "ö") \
                .replace("Ã·", "÷") \
                .replace("Ã¸", "ø") \
                .replace("Ã¹", "ù") \
                .replace("Ãº", "ú") \
                .replace("Áº", "ú") \
                .replace("Ã»", "û") \
                .replace("Ã¼", "ü") \
                .replace("Á¼", "ü") \
                .replace("Ã½", "ý") \
                .replace("Ã¾", "þ") \
                .replace("Ã¿", "ÿ")
